[VBV-1530] Improve UX in case certificate is not valid
Show (and logs) the reason for not accepting the certificate, e.g.:
 > Importing ssl certificate failed for server: https://localhost:443,
 > error: NotBefore: Sun Dec 31 10:56:00 EET 2017

Change-Id: I744a2f5bf67a5a214a9c00a7df0045503f816f61
Reviewed-on: http://bellevue-ci.eng.vmware.com:8080/15133
Closures-Verified: jenkins <jenkins@vmware.com>
Bellevue-Verified: jenkins <jenkins@vmware.com>
Upgrade-Verified: jenkins <jenkins@vmware.com>
CS-Verified: jenkins <jenkins@vmware.com>
Reviewed-by: Stanislav Hadjiiski <hadjiiskis@vmware.com>