Fix for the upgrade job
The problem was compilation error because of a change submitted
yesterday.
- Adapted the code with the new changes.

Change-Id: Ia540390a11f7153e7568740e955acb4664a0b52e
Reviewed-on: https://bellevue-ci.eng.vmware.com:8080/27438
Bellevue-Verified: e_vcoauto_glob_1 <e_vcoauto_glob_1@vmware.com>
Closures-Verified: e_vcoauto_glob_1 <e_vcoauto_glob_1@vmware.com>
CS-Verified: e_vcoauto_glob_1 <e_vcoauto_glob_1@vmware.com>
Upgrade-Verified: e_vcoauto_glob_1 <e_vcoauto_glob_1@vmware.com>
Reviewed-by: Lazarin Lazarov <llazarov@vmware.com>