Fix for the upgrade job
The problem was compilation error because of a change submitted
yesterday.
- Adapted the code with the new changes.

Change-Id: Iaa9613cc274177a44453d6e8fec45d776ea2fc2c
Reviewed-on: https://bellevue-ci.eng.vmware.com:8080/27435
Upgrade-Verified: jenkins <jenkins@vmware.com>
Reviewed-by: Lazarin Lazarov <llazarov@vmware.com>
Bellevue-Verified: e_vcoauto_glob_1 <e_vcoauto_glob_1@vmware.com>
Closures-Verified: e_vcoauto_glob_1 <e_vcoauto_glob_1@vmware.com>
CS-Verified: e_vcoauto_glob_1 <e_vcoauto_glob_1@vmware.com>