Fix for  g.default.toBytes is not a function
Caused by a recent refactor where the utils were separated in a common module

Change-Id: I0347db40cbcd4707b66f5dd5509167e3722a6314
Reviewed-on: http://bellevue-ci.eng.vmware.com:8080/7611
Reviewed-by: Tony Georgiev <tgeorgiev@vmware.com>
Compute-Verified: jenkins <jenkins@vmware.com>
Upgrade-Verified: jenkins <jenkins@vmware.com>
Bellevue-Verified: jenkins <jenkins@vmware.com>
CS-Verified: jenkins <jenkins@vmware.com>