[VBV-2979] Use local npm repository
- Switch to local npm repository
- Fix broken build by syncing prod & dev versions
- Update expired test certificate
- Fix docker hub registry config
  Docker Hub has changed their API once again, this time removing the
  /v1/_ping endpoint, which effectively breaks the ability to configure
  docker hub as a registry in Admiral.
  The following change tries to avoid the problem by introducing an
  alternative way to ping docker hub as it is being configured as a
  registry.
- Update latest changes on DockerProvisioningOnCoreOs IT
- KubernetesEntityDataCollectionTest - java.lang.AssertionError:
  expected:<1> but was:<0> -> problem was the query was not created
  properly

Change-Id: I8288521b59fc980262c555f716b0566bde24016c
Reviewed-on: https://bellevue-ci-gerrit.eng.vmware.com:443/c/88744
Bellevue-Verified: jenkins <jenkins@vmware.com>
PG-Verified: jenkins <jenkins@vmware.com>
Upgrade-Verified: jenkins <jenkins@vmware.com>
Reviewed-by: Miroslav Shipkovenski <mshipkovenski@vmware.com>
CS-Verified: jenkins <jenkins@vmware.com>
(cherry picked from commit 556b4e6c855e7a82ae2608699989a8bf95283a0a)
Reviewed-on: https://bellevue-ci-gerrit.eng.vmware.com:443/c/99761
Reviewed-by: Lazarin Lazarov <llazarov@vmware.com>
Upgrade-Verified: e_vcoauto_glob_1 <e_vcoauto_glob_1@vmware.com>